name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Grant execute permission for init.sh
      run: chmod +x init.sh
    - name: Grant execute permission for makeffi.sh
      run: chmod +x makeffi.sh
    - name: Grant execute permission for makepy.sh
      run: chmod +x makepy.sh
    - name: init
      run: ./init.sh
    - name: makeffi
      run: ./makeffi.sh
    - name: makepy
      run: ./makepy.sh
